GraniteHouse_sw2/GraniteHouse_sw2/Areas/Admin/Controllers/AdminUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GraniteHouse_sw2.Data;
using GraniteHouse_sw2.Models;
using GraniteHouse_sw2.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GraniteHouse_sw2.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.SuperAdminEndUser)]
    [Area("Admin")]
    public class AdminUsersController : Controller
    {
        private readonly ApplicationDbContext _db;

        public AdminUsersController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View(_db.ApplicationUser.ToList());
        }



        //Get Edit

        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || id.Trim().Length == 0)
            {
                return NotFound();
            }

            var userFromDb = await _db.ApplicationUser.FindAsync(id);
            if (userFromDb == null)
            {
                return NotFound();
            }

            return View(userFromDb);
        }


        //Post Edit 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(string id, ApplicationUser applicationUser)
        {
            if (id != applicationUser.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {

                ApplicationUser userFromDb = _db.ApplicationUser.Where(u => u.Id == id).FirstOrDefault();
                userFromDb.Name = applicationUser.Name;
                userFromDb.PhoneNumber = applicationUser.PhoneNumber;

                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(applicationUser);

        }



        //Get Delete
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || id.Trim().Length == 0)
                return NotFound();

            var userFromDb = await _db.ApplicationUser.FindAsync(id);
            if (userFromDb == null)
                return NotFound();
            return View(userFromDb);
        }

        //Post Delete 
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(string id)
        {



            ApplicationUser userFromDb = _db.ApplicationUser.Where(u => u.Id == id).FirstOrDefault();
            userFromDb.LockoutEnd = DateTime.Now.AddYears(1000);


            _db.SaveChanges();
            return RedirectToAction(nameof(Index));


        }

    }
}

GraniteHouse_sw2/GraniteHouse_sw2/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using GraniteHouse_sw2.Data;
using GraniteHouse_sw2.Models;
using GraniteHouse_sw2.Models.ViewModel;
using GraniteHouse_sw2.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting.Internal;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GraniteHouse_sw2.Controllers

{
    [Authorize(Roles = SD.SuperAdminEndUser)]
    [Area("Admin")]
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly HostingEnvironment _hostingEnvironment;


        [BindProperty]
        public ProductViewModel ProductsVM { get; set; }
        public ProductsController(ApplicationDbContext db, HostingEnvironment hostingEnvironment)
        {
            _db = db;
            _hostingEnvironment = hostingEnvironment;
            ProductsVM = new ProductViewModel()
            {
                ProductTypes = _db.ProductTypes.ToList(),
                SpecialTags = _db.SpecialTags.ToList(),
                Products = new Models.Products()
            };
        }
        public async Task<IActionResult> Index()
        {
            var Products = _db.Products.Include(m => m.ProductTypes).Include(m => m.SpecialTags);

            return View(await Products.ToListAsync());
        }
        // get: Products Create

        public IActionResult Create()
        {
            return View(ProductsVM);
        }
        //Post : Products Create
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> CreatePost()
        {
            if (!ModelState.IsValid)
            {
                return View(ProductsVM);
            }
            _db.Products.Add(ProductsVM.Products);
            await _db.SaveChangesAsync();


            //image being saved

            string WebRootPath = _hostingEnvironment.WebRootPath;
            var files = HttpContext.Request.Form.Files;
            var productsFromDb = _db.Products.Find(ProductsVM.Products.Id);

            if (files.Count != 0)
            {
                //image has been uploaded
                var uploads = Path.Combine(WebRootPath, SD.ImageFolder);
                var extention = Path.GetExtension(files[0].FileName);
                using (var filestram = new FileStream(Path.Combine(uploads, ProductsVM.Products.Id + extention), FileMode.Create))

                {
                    files[0].CopyTo(filestram);
                }

                productsFromDb.Image = @"\" + SD.ImageFolder + @"\" + ProductsVM.Products.Id + extention;



            }

            else
            {
                var uploads = Path.Combine(WebRootPath, SD.ImageFolder + @"\" + SD.DefaultProductImage);
                System.IO.File.Copy(uploads, WebRootPath + @"\" + SD.ImageFolder + @"\" + ProductsVM.Products.Id + ".jfif");
                productsFromDb.Image = @"\" + SD.ImageFolder + @"\" + ProductsVM.Products.Id + ".jfif";


            }
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));


        }


        //Edit :Get

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            ProductsVM.Products = await _db.Products.Include(m => m.SpecialTags).Include(m => m.ProductTypes).SingleOrDefaultAsync(m => m.Id == id);
            if (ProductsVM.Products == null)
                return NotFound();

            return View(ProductsVM);
        }



        //Post : Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProductViewModel productsvm)
        {
            if (ModelState.IsValid)
            {
                string webRootPath = _hostingEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;

                var productFromDb = _db.Products.Where(m => m.Id == productsvm.Products.Id).FirstOrDefault();

                if (files.Count > 0 && files[0] != null)
                {
                    var uplaods = Path.Combine(webRootPath, SD.ImageFolder);
                    var extension_new = Path.GetExtension(files[0].FileName);
                    var extension_old = Path.GetExtension(productFromDb.Image);

                    if (System.IO.File.Exists(Path.Combine(uplaods, ProductsVM.Products.Id + extension_old)))
                    {
                        System.IO.File.Delete(Path.Combine(uplaods, ProductsVM.Products.Id + extension_old));
                    }

                    using (var fileStream = new FileStream(Path.Combine(uplaods, ProductsVM.Products.Id + extension_new), FileMode.Create))

                    {
                        files[0].CopyTo(fileStream);
                    }

                    ProductsVM.Products.Image = @"\" + SD.ImageFolder + @"\" + productsvm.Products.Id + extension_new;


                }

                if (ProductsVM.Products.Image != null)
                {
                    productFromDb.Image = ProductsVM.Products.Image;
                }

                productFromDb.Name = ProductsVM.Products.Name;
                productFromDb.Price = ProductsVM.Products.Price;
                productFromDb.Available = ProductsVM.Products.Available;
                productFromDb.ProductTypeId = ProductsVM.Products.ProductTypeId;
                productFromDb.SpecialTagId = ProductsVM.Products.SpecialTagId;
                productFromDb.ShadeColor = ProductsVM.Products.ShadeColor;
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(ProductsVM);
        }

        //Get : Details 
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            ProductsVM.Products = await _db.Products.Include(m => m.SpecialTags).Include(m => m.ProductTypes).SingleOrDefaultAsync(m => m.Id == id);
            if (ProductsVM.Products == null)
                return NotFound();

            return View(ProductsVM);
        }


        //Get : Delete 
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            ProductsVM.Products = await _db.Products.Include(m => m.SpecialTags).Include(m => m.ProductTypes).SingleOrDefaultAsync(m => m.Id == id);
            if (ProductsVM.Products == null)
                return NotFound();

            return View(ProductsVM);
        }

        //Post : Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, ProductViewModel productsvm)
        {
            string webRootPath = _hostingEnvironment.WebRootPath;
            Products products = await _db.Products.FindAsync(id);


            if (products == null)
            {
                return NotFound();
            }
            else
            {
                var uplaods = Path.Combine(webRootPath, SD.ImageFolder);
                var extension = Path.GetExtension(products.Image);

                if (System.IO.File.Exists(Path.Combine(uplaods, products.Id + extension)))
                {
                    System.IO.File.Delete(Path.Combine(uplaods, products.Id + extension));


                }

                _db.Products.Remove(products);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));


            }
        }
    }
}

GraniteHouse_sw2/GraniteHouse_sw2/Areas/Admin/Controllers/SpecialTagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GraniteHouse_sw2.Data;
using GraniteHouse_sw2.Models;
using GraniteHouse_sw2.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GraniteHouse_sw2.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.SuperAdminEndUser)] 
    [Area("Admin")]
    public class SpecialTagsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public SpecialTagsController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View(_db.SpecialTags.ToList());
        }



        // GET Create Action Method
        public IActionResult Create()
        {
            return View();
        }

        //POST Create Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SpecialTags specialTags)
        {
            if (ModelState.IsValid) 
            {
                _db.Add(specialTags);
                
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(specialTags);
        }

        //Get Edit Method
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var specialTags = await _db.SpecialTags.FindAsync(id);
            if (specialTags == null)
            {
                return NotFound();
            }
            return View(specialTags);
        }

        //Post Edit Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, SpecialTags specialTags)
        {
            if (id != specialTags.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.Update(specialTags);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(specialTags);
        }


        //Get Details Method
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var specialTags = await _db.SpecialTags.FindAsync(id);
            if (specialTags == null)
            {
                return NotFound();
            }
            return View(specialTags);
        }


        //Get Delete Method
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var specialTags = await _db.SpecialTags.FindAsync(id);
            if (specialTags == null)
            {
                return NotFound();
            }
            return View(specialTags);
        }

        //Post Delete Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {

            var specialTags = await _db.SpecialTags.FindAsync(id);
            _db.SpecialTags.Remove(specialTags);

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }
    }
}

GraniteHouse_sw2/GraniteHouse_sw2/Views/Shared/_AppointmentCustomerDetails.cshtml
@model GraniteHouse_sw2.Models.Appointments

<h4 class="text-success">Appointment Details</h4>

<div style="height:100%; background-color:aliceblue;" class="container border">
    <div class="col-12">
        <div class="row" style="padding-top:10px;">
            <div class="col-2">
                Full Name
            </div>
            <div class="col-3">
                <input asp-for="@Model.CustomerName" readonly class="form-control" />
            </div>
            <div class="col-2">

            </div>
            <div class="col-2">
                Email
            </div>
            <div class="col-3">
                <input asp-for="@Model.CustomerEmail" readonly class="form-control" />
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="row" style="padding-top:10px;">
            <div class="col-2">
                Phone Number
            </div>
            <div class="col-3">
                <input asp-for="@Model.CustomerPhoneNumber" readonly class="form-control" />
            </div>
            <div class="col-2">

            </div>
            <div class="col-2">
                Appointment Date
            </div>
            <div class="col-3">
                <input asp-for="@Model.AppointmentDate" readonly class="form-control" />
            </div>
        </div>
    </div>

</div>

GraniteHouse_sw2/GraniteHouse_sw2/Views/Shared/_AppointmentProductDetails.cshtml
@model List<GraniteHouse_sw2.Models.Products>
@if (Model.Count > 0)
{
    <table class="table table-striped" width="100%">
        <tr class="table-info">
            <th style="text-align:center; width:20%"></th>
            <th style="text-align:center; width:20%">
                <label asp-for="@Model.FirstOrDefault().Name"></label>
            </th>
            <th style="text-align:center; width:20%">
                <label asp-for="@Model.FirstOrDefault().Price"></label>
            </th>
            <th style="text-align:center; width:20%">
                <label asp-for="@Model.FirstOrDefault().ShadeColor"></label>
            </th>
            <th style="text-align:center; width:20%">
                <label asp-for="@Model.FirstOrDefault().ProductTypes.Name"></label>
            </th>
            <th style="text-align:center;"></th>
        </tr>
        @foreach (Products item in Model)
        {
            <tr style="padding:50px;">
                <td>
                    <a asp-area="Customer" asp-controller="Home" asp-action="Details" asp-route-id="@item.Id">
                        <img src="@item.Image" width="100%" style="margin:auto; display:block; border-radius:5px; border:1px solid #bbb9b9;" />
                    </a>
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(c => item.Name)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(c => item.Price)
                </td>

                <td style="text-align:center">
                    @Html.DisplayFor(c => item.ShadeColor)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(c => item.ProductTypes.Name)
                </td>
            </tr>
        }
    </table>
}
else
{
    <div>No items added to the shopping cart...</div>
}

GraniteHouse_sw2/GraniteHouse_sw2/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using GraniteHouse_sw2.Extensions
@using GraniteHouse_sw2.Utility

@inject IHttpContextAccessor HttpContextAccessor


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GraniteHouse_sw2</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/jquery-ui.css" />
        <link rel="stylesheet" href="~/css/jquery.timepicker.css" />
        <script src="https://kit.fontawesome.com/79b5337f83.js" crossorigin="anonymous"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />

        <link rel="stylesheet" href="~/css/jquery-ui.css" />
        <link rel="stylesheet" href="~/css/jquery.timepicker.css" />

        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <script src="https://kit.fontawesome.com/79b5337f83.js" crossorigin="anonymous"></script>
    </environment>
</head>
<body>






    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top  ">
        <a class="navbar-brand" href="#">Granite House</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- <div class="collapse navbar-collapse" id="navbarSupportedContent">-->
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">


                <li class="nav-item"><a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home  </a></li>
                @if (User.IsInRole(SD.SuperAdminEndUser))
                {
                    <li class="nav-item"><a class="nav-link" asp-area="Admin" asp-controller="ProductTypes" asp-action="Index"> Product Types</a></li>
                    <li class="nav-item"><a class="nav-link" asp-area="Admin" asp-controller="SpecialTags" asp-action="Index"> Special Tags</a></li>
                    <li class="nav-item"><a class="nav-link" asp-area="Admin" asp-controller="Products" asp-action="Index"> Products </a></li>


                    <li class="nav-item"><a class="nav-link" asp-area="Admin" asp-controller="AdminUsers" asp-action="Index">Admin Users  </a></li>

                }



                @if (User.IsInRole(SD.SuperAdminEndUser) || User.IsInRole(SD.AdminEndUser))
                {
                    <li class="nav-item"><a class="nav-link" asp-area="Admin" asp-controller="Appointments" asp-action="Index"> Appointments </a></li>
                }

                @if (HttpContextAccessor.HttpContext.Session.Get<List<int>>("ssShoppingCart") != null)
                {
                    <li>
                        <a asp-area="Customer" asp-controller="ShoppingCart" asp-action="Index" class="nav-link">
                            <i class="fas fa-shopping-cart"></i> &nbsp;
                            @{
                                var count = HttpContextAccessor.HttpContext.Session.Get<List<int>>("ssShoppingCart").Count;
                            }
                            (@count)
                        </a>
                    </li>

                }
                else
                {
                    <li>
                        <a asp-area="Customer" asp-controller="ShoppingCart" asp-action="Index" class="nav-link">
                            <i class="fas fa-shopping-cart"></i> &nbsp;

                            (0)
                        </a>
                    </li>
                }
            </ul>


        </div>


        <div>

            <Partial name="_LoginPartial" />

        </div>
    </nav>
























    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - GraniteHouse_sw2</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/jquery-ui.js" asp-append-version="true"></script>
        <script src="~/js/jquery.timepicker.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/jquery-ui.js" asp-append-version="true"></script>
        <script src="~/js/jquery.timepicker.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

GraniteHouse_sw2/GraniteHouse_sw2/Views/Shared/_TableButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


<td style="width:150px">
    <div class="btn-group role="group">
        <a type="button" class="btn btn-primary" href="@Url.Action("Edit/"+Model)">
            <i class="fas fa-edit"></i>
        </a>
        <a type="button" class="btn btn-success" href="@Url.Action("Details/"+Model)">
            <i class="fas fa-list-alt"></i>
        </a>
        <a type="button" class="btn btn-danger" href="@Url.Action("Delete/"+Model)">
            <i class="fas fa-trash"></i>
        </a>
    </div>
</td>